apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          volumeMounts:
            - name: secret-volume
              mountPath: {{ .Values.secret.mountPath }}
              readOnly: true
          resources:
            requests:
              memory: "30Mi"
              cpu: "30m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /api/healthcheck
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 30
          startupProbe:
            httpGet:
              path: /api/healthcheck
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
      volumes:
        - name: secret-volume
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "{{ .Release.Name }}-storage-class"
